[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "79df4e07f1964733a4093e779d2dd59204980c84"
os = "macos"

    [[libCEED.download]]
    sha256 = "a6af06f6af66ab063d1ea87f1c1c0a5694fe095eeb14c2e16ec6bd3ac33914a5"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.aarch64-apple-darwin.tar.gz"
[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "4ded99924d031c8a33defd54768b28bd60d37ee6"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "618e86386d1ecf04fb87f21002e764b517c4aaedf5125318560bc850c545757f"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.aarch64-linux-gnu.tar.gz"
[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "2788fea154c508f03ba2e25231ecb6540a454c35"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "b550cf11ae27aeeff7fe50016f663c1951955128a810667ddf192bf166f2a118"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.aarch64-linux-musl.tar.gz"
[[libCEED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "08ded64fc770ec1371e302059fe1625ad0d601e8"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "91f256eccd479d4d265d289624e73d4d0413bd5b6cd3f0ab539a50c7c9531bd6"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.armv6l-linux-gnueabihf.tar.gz"
[[libCEED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ee262a45fd12f7baa8cf9fc58226a7294799b38"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "5ffa74314fe8de123cd4613658d5e768b5631db5168a84494472b10ec191e87e"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.armv6l-linux-musleabihf.tar.gz"
[[libCEED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9aed8c5261b1448bbc79df45a97241224f2e5ef1"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "3779ac896685462b71534388d8f79090c509b156a893f22c5339cb8a978359cf"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.armv7l-linux-gnueabihf.tar.gz"
[[libCEED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a42710432fa0d657fda73138f7e2622cd97d7621"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "672fc5ab33855d59c911b3b4eb80cfaaebad601921d7086a6754ee6e2ad5356c"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.armv7l-linux-musleabihf.tar.gz"
[[libCEED]]
arch = "i686"
git-tree-sha1 = "9a4cafa506f7cc927642dcaafd09c919d56a6c42"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "17fe9e0f8462ae1a5ed4119a2f4badae2c7c9492ae0cce86b503d4ed8bd53202"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.i686-linux-gnu.tar.gz"
[[libCEED]]
arch = "i686"
git-tree-sha1 = "6ca09a7c0c0b73e69f33cfd3c17b0a41ffe42913"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "64c06dd6b4f68a7dc265550e0d9a58051499894aa833889ff9b6a48c73f47532"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.i686-linux-musl.tar.gz"
[[libCEED]]
arch = "powerpc64le"
git-tree-sha1 = "bc1334073b970021f720015ae44a0f8271a0f7da"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "ce4fa32590b0d9571a3b3462cfab5cf9045e2654dd5f82c0b0fdb7be0598b8a4"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.powerpc64le-linux-gnu.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "ba609302beae572c1d8e8354b7425a152bd18946"
os = "macos"

    [[libCEED.download]]
    sha256 = "66c741b941dfb8b7430c9e3c42b7fb97eee5fe44b6740c53abfea0d8312d5f98"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.x86_64-apple-darwin.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "6209954124548de892b84062883f48fa2e335986"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "a7dde98c6ae90e131882575e85a24092ca750f7a521948f12c247751b11bd25b"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.x86_64-linux-gnu.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "f7d85fc6250059100ca1915903d8b1992294c5f0"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "7bb522dd5e7539ccdb1fc1c01a689b5a321f2ffd98c673c1ff1ca7eaf2102f6f"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.x86_64-linux-musl.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "a9a7e55738d16c42f50feb81cb6f3b4ebf50aa1c"
os = "freebsd"

    [[libCEED.download]]
    sha256 = "c54c0daf3a5fa0be47c7516a074ac236678393c0889bc20836f36557f00263c9"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.0+0/libCEED.v0.10.0.x86_64-unknown-freebsd.tar.gz"
