[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "2faa987d5345ec6c3a6930be39e1235482049e92"
os = "macos"

    [[libCEED.download]]
    sha256 = "614260b4eb0799e7f3dbd6192b268768ce761557fe84c790200db707b4bb6f0a"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.aarch64-apple-darwin.tar.gz"
[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "24431c28ac27b5321b70bf1ce0b1272c220a98d3"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "f90662377adb0bd14338006921791e5513e2b02eee9bcd9e0092de9964186b70"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.aarch64-linux-gnu.tar.gz"
[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "0edab46e22bf8b61d482617fd1770ad50b9d50b3"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "7df56faf29b005014300c6f6d6fbb2f155cf883f073350dd97af48bc0ad02806"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.aarch64-linux-musl.tar.gz"
[[libCEED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ca306f34f1899e5050c86ac3ab1dbd373db12334"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "12d3058fdf00359ea3e9807a26c4a2de7aeedc0b3fce992f87e1619f0ade25fb"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.armv6l-linux-gnueabihf.tar.gz"
[[libCEED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e12655cf8241eeecab80471f51b056378805f4b9"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "333ce5c7dc261535117ceca558dd111b6f94a708550cedc0ca0264c883b45d96"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.armv6l-linux-musleabihf.tar.gz"
[[libCEED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c7f94258cc003d93960cc4d37c48e3e955163b95"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "37a4ab3bf593f4432ab51f3f84848c57ec97a759b942d174018bd2b5e98f814b"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.armv7l-linux-gnueabihf.tar.gz"
[[libCEED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "669eceee74cdfb7554cf153aeb392930c070b71e"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "01f087438dab7294063aa3d14ad47a62e526996bf7c0953092b64bb8bc092abd"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.armv7l-linux-musleabihf.tar.gz"
[[libCEED]]
arch = "i686"
git-tree-sha1 = "33bf2a2c313a102dfb321384f99815ac37d6f147"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "41cc3b4d39ecd9fbf3e9697f7f5d0f0704e7643b15196682a99e1d21048d02b0"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.i686-linux-gnu.tar.gz"
[[libCEED]]
arch = "i686"
git-tree-sha1 = "c92bf3998c8498eaf0e98a048c7a1378fe3315c3"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "b33ae110bc1f75cd78c081e813d6ab2e37007973bd870ee801dd03088bb3212b"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.i686-linux-musl.tar.gz"
[[libCEED]]
arch = "powerpc64le"
git-tree-sha1 = "738116bc8adafdb71433de477450efe97501fcdb"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "e90026fa31d785f5f0402edccdf2faed20997d98dadc99e88aa3bb2eca8b368d"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.powerpc64le-linux-gnu.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "6e6f7a675cd264978fb08eeec6881ec89e586a26"
os = "macos"

    [[libCEED.download]]
    sha256 = "14e14bf5c92294ac14547bc25b524bfb8ab878ace1eeaa826fb2648b63ddd361"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.x86_64-apple-darwin.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "799c65beeca06007c1c27389c44f2bf6ed5e199a"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "cb545167cf6fcdd4cac12b9c03d7383186775190237b9fe6ca8375fe36827989"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.x86_64-linux-gnu.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "b06ec1889b1c2bda27d55e676d19a41b0405531d"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "5bf5f86c7f3d22aa8a4d935af65c45fd2a5a6a35341935668c5f2260d85c59c1"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.x86_64-linux-musl.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "424894e1a86f644f9dc32d12607ab58f9b0934cf"
os = "freebsd"

    [[libCEED.download]]
    sha256 = "209e8b7528ba3dbd8ae62f5e166ec3dbdcf6679f4c8e59a13c2d351fbafda39e"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.12.0+0/libCEED.v0.12.0.x86_64-unknown-freebsd.tar.gz"
