[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "2ceb0f8ca280f29b2deb4f65f739eeb9ab8cd175"
os = "macos"

    [[libCEED.download]]
    sha256 = "f43f510f6733a1716315cd49420123049c58521865b8f1edc1cd3f1c2b910718"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.aarch64-apple-darwin.tar.gz"
[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "c4ca07286acbdd27d3f7f1f366314c8a46fab03c"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "f23b9a2e5d5a75bbab1ceffb5c247faa9f7fbd5f683060066438f4c2a783c293"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.aarch64-linux-gnu.tar.gz"
[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "b28e10ca5ebb1c9db1f78cb914a42dbd514be89a"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "eff6664167cf9376db219fcd3ff891f2ca6fd41eafa23063902931566333b8e5"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.aarch64-linux-musl.tar.gz"
[[libCEED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6d5db7230be35609ae6168eed7ee0fbdac283b71"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "f3203b3e77d9f934d5473817ad5a8e6f4bc5029b31a6740181e601dc6b709c89"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.armv6l-linux-gnueabihf.tar.gz"
[[libCEED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "01ac24729f772bffe9544b73af9abec7c9037994"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "6548685a3edbf6410259be3f8347727abc11e1ef00f9c82124a3c8edb41bbd24"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.armv6l-linux-musleabihf.tar.gz"
[[libCEED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f91cc4d7eb95e8d12328f4ae652fdf3e8a9a43dc"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "c9e533828c16744ea7d84020779b335fa16afef83df358c9ce843fb8f9fcea0c"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.armv7l-linux-gnueabihf.tar.gz"
[[libCEED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "97bbfda74cbee7393dfb86fd56e63500ed833039"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "7d0f7701fb0f10fb33bf2fdb83ede301e622e74012ebb328234afa09488afd85"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.armv7l-linux-musleabihf.tar.gz"
[[libCEED]]
arch = "i686"
git-tree-sha1 = "7edd48874362d71dba59ef90f7d894857ca57eba"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "bf1c0ff8218eb8ca7a74ff973a73c086655411d1efe110a59346778b3ae6cc7e"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.i686-linux-gnu.tar.gz"
[[libCEED]]
arch = "i686"
git-tree-sha1 = "2d643e13f85505570ff8aad5485d782a49a3dae6"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "283421e5c6cce36070ccb9b8cab6c7fb4245d9611c738616d23d339ae212d8be"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.i686-linux-musl.tar.gz"
[[libCEED]]
arch = "powerpc64le"
git-tree-sha1 = "0c86bf5d8b7cf52d45a9fbb6420bbc7c6c1cbd8f"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "6f1ef21af36a6b02b1e288eb4d09632a7e2113558a8b6796f1548bf73611b5ea"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.powerpc64le-linux-gnu.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "3f6b3392c663d3ced67ad120205c4caf7e68c2a6"
os = "macos"

    [[libCEED.download]]
    sha256 = "64b8fa9c8174d89f4f943fb28ac337849f4f710e55ab18c7426be05f89029ab0"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.x86_64-apple-darwin.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "4b61317d4883e3c908c8dcba2dd04e0613445979"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "cd281852d69abb149d92729fed4caf883fac754cc40641d56f11f372775693fa"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.x86_64-linux-gnu.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "921b9d506889a2859d8eee9b8eea5abc89f3524d"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "c9c0be88ac77b192ef560601dc4b5bedd68b2abbafbccef2aa699d6f10d375eb"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.x86_64-linux-musl.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "eb7ba2e1b790939e28f9b4b35993f81d36d1b6fe"
os = "freebsd"

    [[libCEED.download]]
    sha256 = "b32f27d5b1683491c712eedfb55bb43f4d07e85d75cd3a1116c8e0edeb5c6c0e"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.11.0+0/libCEED.v0.11.0.x86_64-unknown-freebsd.tar.gz"
