[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "dbc0584e3faf3b9e0a86278ac63dfb73f4e961df"
os = "macos"

    [[libCEED.download]]
    sha256 = "87aeff62f27c848ec440ad3165af345daa7da3fa5ed05bf70d8d1775017cd9be"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.aarch64-apple-darwin.tar.gz"
[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "0bdce51683088bb17ca81d0684b7981575194067"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "b27071b586d915553b7af5b0d8dfe481ead0cc2fcea8d8b6e95c204bb8920dc0"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.aarch64-linux-gnu.tar.gz"
[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "bb2faae5223c2e65cb9ee156a736a11749f6b73f"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "96d059d54e10699a6a64353c9b863abf9eaba74a7fe31c6a7856f75f27c6241d"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.aarch64-linux-musl.tar.gz"
[[libCEED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b587d0b336d16de036b0febe51044b76cc7cf486"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "c1a0ac6a042d3254952c605ce3a2f97e3ead85c5f0c2ceec6a30d43664436980"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.armv6l-linux-gnueabihf.tar.gz"
[[libCEED]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b957149e2b929ce6662696bcc2390b9575ec88a4"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "4e461d7a71b2279924fe23ea21e53464b7a2a811ae69bc075efcf4016af3ad58"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.armv6l-linux-musleabihf.tar.gz"
[[libCEED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dea76eee03a064dbaaf8effe6ff38035fc20f629"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "9c725bd34c765efa5cb4326953c3eb541fe99a465598d8755ec276b04f55bb3a"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.armv7l-linux-gnueabihf.tar.gz"
[[libCEED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "491500f1ff789f8b0ee2e59ed9c83d7fe9b01b25"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "f030a4bba7628f77e84d02aac49bbdd3e824281c7922d25493be35ea930a3b59"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.armv7l-linux-musleabihf.tar.gz"
[[libCEED]]
arch = "i686"
git-tree-sha1 = "6f1d51a31facc1da556413fb1a3dfd7a246275c1"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "c2bbd6b0e7ee73220072acb19bc93c4e1afca69208d26c2ad8b087b58af44292"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.i686-linux-gnu.tar.gz"
[[libCEED]]
arch = "i686"
git-tree-sha1 = "2a36a402d41486d0151e6e5bfd82b4a24dfe48eb"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "aa19339a379ef4ec94574f72e56880fe0ef90d2421861aa656361cb45e2309c6"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.i686-linux-musl.tar.gz"
[[libCEED]]
arch = "powerpc64le"
git-tree-sha1 = "6e1f5b76a9c0683589f5041d493ed18e0fbcc1bf"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "9ce6752cbadb616e8e576f074e3fbd54a84847b4880db70edd0a084ed49bba1a"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.powerpc64le-linux-gnu.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "64412fe119ca4607d9f6dbc8e751082f21e7ac31"
os = "macos"

    [[libCEED.download]]
    sha256 = "9113984360abd78982612b45f59ffdbc8af608aaa7056bfb568b69dc9f4eae94"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.x86_64-apple-darwin.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "1fb8a0807afab08d787bcf66ac722edf1f870de6"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "d36433eb8a50c7fb523fd674c54dab3b911419db9db8b6580f40c3bdf4bfa54b"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.x86_64-linux-gnu.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "796cb00eba53a6044f6a66d39d4f75d0dc4b2d15"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "27c1b41781de5af5e023d7d55dc632e33d11a1205c0f7e47daa2591d5ecf3626"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.x86_64-linux-musl.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "ecf64961ede15a6c7690eb23e2c99356834dccfa"
os = "freebsd"

    [[libCEED.download]]
    sha256 = "ce28a2f3ba21d269536adb197ce85182eb3650416f88f48c4834ca928aa69b60"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.10.1+0/libCEED.v0.10.1.x86_64-unknown-freebsd.tar.gz"
