[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "aa0bda0307540c004ca5144b72e9aa6f6449cfd1"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "c2dd8cd172626fc3f342418219d546233af67cafcbc2c44434746127a16e5ceb"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.9.0+0/libCEED.v0.9.0.aarch64-linux-gnu.tar.gz"
[[libCEED]]
arch = "aarch64"
git-tree-sha1 = "ede9439561fea72d62c58ae743b71e36be20f07f"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "9adbb6f4533031495fb5d6bc48e4dfb67bd0bfda4288b2888913ac375e29c59a"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.9.0+0/libCEED.v0.9.0.aarch64-linux-musl.tar.gz"
[[libCEED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fe0cfa481937ed6ac527d0e1a0a1d700655174b8"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "234f052b8d7abbf05e40e9c3829a23acfd2b3566119e953ef17d22a888377e17"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.9.0+0/libCEED.v0.9.0.armv7l-linux-gnueabihf.tar.gz"
[[libCEED]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "341035aa74fcb230c37131aac4118c56cfd12c2d"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "b8062ddf96d682ac058d5b20ef3e58482e1b01270f53eb33c68a97e4f1619cd7"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.9.0+0/libCEED.v0.9.0.armv7l-linux-musleabihf.tar.gz"
[[libCEED]]
arch = "i686"
git-tree-sha1 = "1d67e0938ec3c7340c8112e5a98ecb056b86b8cc"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "2e7bd55134d066bd37480573b6071633761a053fe4184aa2cdf4726271450a0b"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.9.0+0/libCEED.v0.9.0.i686-linux-gnu.tar.gz"
[[libCEED]]
arch = "i686"
git-tree-sha1 = "b0a75408bb976878aeeb1744a5dc91b6bdf05a35"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "c0ef63e74901f2f646fcad0f6604e06eb16b992a3ec8cd19e9211d4f96166895"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.9.0+0/libCEED.v0.9.0.i686-linux-musl.tar.gz"
[[libCEED]]
arch = "powerpc64le"
git-tree-sha1 = "91c145a3e0bb2107612c2ccb6fef6ba972d9089e"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "55b14c60469252eee7a8761e9bc62838140706b0f59d12c5c4286e6919f17801"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.9.0+0/libCEED.v0.9.0.powerpc64le-linux-gnu.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "577b9812c813815d2bb98789d750c40977619ce5"
os = "macos"

    [[libCEED.download]]
    sha256 = "43ac93c2cb85e6758d3bffa20ff1e48a8d82fdf84e95d7e8173dc528e572c6c2"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.9.0+0/libCEED.v0.9.0.x86_64-apple-darwin.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "75fa2a417fed92d486672f35efcf7a23c6be6b15"
libc = "glibc"
os = "linux"

    [[libCEED.download]]
    sha256 = "ed1a10a769a2c53f7f1ace6121c4c9879351a83e057d0504a52143bdf1e04a57"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.9.0+0/libCEED.v0.9.0.x86_64-linux-gnu.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "50522ddcf60a3242abd3a73d8adba4b1daf73f54"
libc = "musl"
os = "linux"

    [[libCEED.download]]
    sha256 = "f539ca715e56b9bb20b9a7b0a477ba0ff7450507c30639c4303c836815315e01"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.9.0+0/libCEED.v0.9.0.x86_64-linux-musl.tar.gz"
[[libCEED]]
arch = "x86_64"
git-tree-sha1 = "d9f336088df46abc8affd7122d0f4b71d54f9474"
os = "freebsd"

    [[libCEED.download]]
    sha256 = "0dccc93c87c65d209e07ec18bc277960719633bf04c8b23adce12f868ac7f94d"
    url = "https://github.com/JuliaBinaryWrappers/libCEED_jll.jl/releases/download/libCEED-v0.9.0+0/libCEED.v0.9.0.x86_64-unknown-freebsd.tar.gz"
