# Autogenerated wrapper script for libCEED_jll for aarch64-apple-darwin
export libceed

JLLWrappers.@generate_wrapper_header("libCEED")
JLLWrappers.@declare_library_product(libceed, "@rpath/libceed.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libceed,
        "lib/libceed.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
