# Autogenerated wrapper script for libCEED_jll for armv7l-linux-gnueabihf
export libceed

JLLWrappers.@generate_wrapper_header("libCEED")
JLLWrappers.@declare_library_product(libceed, "libceed.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libceed,
        "lib/libceed.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
